GET {{host}}/meme/
token: {{token}}

> ./responseGetHandler.js

###
GET {{host}}/meme/{{idMeme}}
token: {{token}}
###

POST {{host}}/meme
token: {{token}}
Content-Type: application/json

{
  "titulo": "mazzon",
  "ano": 2000,
  "descricao": "huehuehue"
}

> ./responseHandler.js

###

PATCH {{host}}/meme/{{idMeme}}
token: {{token}}
Content-Type: application/json

{
  "ano": 2005
}

###

DELETE {{host}}/meme
token: {{token}}
Content-Type: application/json

{
  "id": "{{idMeme}}"
}

###
